server:
  port: 3003
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: payflow-admin-server
  datasource:
    # 主数据源 - admin 库
    admin:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/payflow_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: root
    # 第二数据源 - cashier 库（订单、支付记录）
    cashier:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/payflow_cashier?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: root
  # Redis：默认连接本机 6379。Windows 下可执行文件目录示例 D:\apps\Redis，需先运行 redis-server.exe
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000ms
  sql:
    init:
      mode: never

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: PayFlowAdminSecretKey2026VeryLongAndSecureKeyForHS256Algorithm
  expiration: 86400000   # 24 hours in milliseconds
  header: Authorization
  prefix: "Bearer "

payflow:
  cors:
    allowed-origins:
      - http://localhost:3001
  cache:
    redis:
      enabled: true
  cashier:
    base-url: http://127.0.0.1:3002
    internal-token: dev-payflow-internal-token
  recon:
    base-url: http://127.0.0.1:3004
    internal-token: dev-payflow-internal-token
  security:
    login-captcha-enabled: true
    login-max-failures: 5
    login-lock-seconds: 900

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
